Failure to find intersects of points on corners/edges of irregular quad.
ecmwf/atlas pull request #101
Opened 2022-03-28 17:28 UTC by odlomax

This is a draft PR associated with #100 

An irregular Quad2D object sometimes fails to evaluate an intersect lying on a corner or edge of the quad.

2022-03-31 09:42 UTC, odlomax commented
@twsearle has given me a thumbs up on this. @wdeconinck are the changes okay with you?

2022-04-04 10:22 UTC, wdeconinck requested changes
Looks great! No issues besides a bit of nitpicking.

2022-04-04 10:22 UTC, wdeconinck commented on src/atlas/grid/detail/partitioner/MatchingMeshPartitionerCubedSphere.cc
> +    const auto tolerance = 2. * std::numeric_limits<double>::epsilon() * N;
```suggestion
    const auto epsilon     = 2. * std::numeric_limits<double>::epsilon() * N;
    const auto edgeEpsilon = epsilon;
    const size_t listSize  = 4;
```

2022-04-04 10:22 UTC, wdeconinck commented on src/atlas/grid/detail/partitioner/MatchingMeshPartitionerCubedSphere.cc
> +        partitioning[i]    = finder.getCell(lonlat, 4, tolerance, tolerance).isect ? mpi::rank() : -1;
```suggestion
        partitioning[i]    = finder.getCell(lonlat, listSize, edgeEpsilon, epsilon).isect ? mpi::rank() : -1;
```

2022-04-04 10:22 UTC, wdeconinck commented on src/atlas/interpolation/element/Quad2D.cc
> +                       check_weight(wght = A - B, edgeEpsilonScaled) ? true : false;
It looks really elegant to have "wght = A + B" or "wght = A - B" inline, but it is a bit confusing. I'm sure you were thinking it too 😉.
Also, perhaps we could spell "wght" out as "weight" 😏

2022-04-04 15:01 UTC, wdeconinck approved these changes

2022-04-04 15:01 UTC, merged