New cubed sphere 2 grid
ecmwf/atlas pull request #245
Opened 2024-11-22 14:51 UTC by mo-jonasganderton

## Description

Initial implementation of a new cubed sphere grid.

@odlomax and @wdeconinck can both have a look over to recommend any changes - I expect this will have changed once everything else has also been implemented.

Using this implementation generates the following lonlat points - n=12, red=tile0, purple=tile5, darkest point of each colour is tij=0, lightest point is tij=143. This matches the sequence of the points in the LFRic cubed sphere.
![CubedSphere_3_0_2](https://github.com/user-attachments/assets/f628744b-03e7-43cf-ad09-f40e6efeb587)

## Impact

Once everything else is also implemented, this makes the cubed sphere more maintainable.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

2024-11-22 14:52 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/atlas?pullRequest=245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/atlas?pullRequest=245) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: odlomax<br/>:x: mo-jonasganderton<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/atlas?pullRequest=245) it.</sub>

2024-11-22 15:10 UTC, odlomax commented on src/atlas/grid/detail/grid/CubedSphere2.h
> +    void lonlat(idx_t n, Point2& point) const {xy(n, point);}
You want to call `projection_.xy2lonlat(xy)` here.

2024-11-22 15:17 UTC, odlomax commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    point[0] = std::atan2(xyz[1], xyz[0]) * rad_to_deg_;
eckit has cartesian to spherical transforms already implemented [here](https://github.com/ecmwf/eckit/blob/develop/src/eckit/geometry/Sphere.h).

Also the degrees to radians constants are already defined [here](https://github.com/ecmwf/atlas/blob/develop/src/atlas/util/Constants.h).

2024-12-11 11:04 UTC, odlomax requested changes
Just some final nitpicks. Cheers, @mo-jonasganderton!

2024-12-11 11:04 UTC, odlomax commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    eckit::geometry::Sphere::convertCartesianToSpherical(xyz_m.norm(), xyz, point);
The radius can set to `1.`, rather than the magnitude of the vector.

2025-01-09 14:47 UTC, odlomax commented
> @wdeconinck, would you be able to have a look at this at your earliest convenience?

I'm haunted by the realisation that "earliest convenience" sounds super passive aggressive. What I meant was, "whenever you can spare the time". 🙃

2025-01-20 13:15 UTC, wdeconinck requested changes
Sorry it has taken me this long @mo-jonasganderton , @odlomax . It looks great! I just have a few minor nitpick-issues to be addressed.

Down the line I hope to remove the number "2" everywhere as in CubedSphere2 :)

2025-01-20 13:15 UTC, wdeconinck commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +PointXYZ CubedSphere2::tangent_to_xyz_coord(PointXY& tan_coord, idx_t tile) const {
```suggestion
PointXYZ CubedSphere2::tangent_to_xyz_coord(const PointXY& tan_coord, idx_t tile) const {
```

2025-01-21 16:19 UTC, mo-jonasganderton commented
Thank you @wdeconinck! I've made a series of improvements following your comments, let me know if there's anything else.

2025-01-22 07:59 UTC, wdeconinck requested changes
Thanks for addressing my suggestions! It looks great now. Just one more thing I had overlooked in my last review.

2025-01-22 07:59 UTC, wdeconinck commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    xyz = lfric_rotations_[tile].transpose() * tan_point;
Since this is called for each point, I'd recommend to store the transposed matrices (in addition or intead?) for such often reuse.

2025-01-22 08:41 UTC, odlomax commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    xyz = lfric_rotations_[tile].transpose() * tan_point;
This is my fault!

2025-01-22 08:42 UTC, odlomax approved these changes
Everything looks great from my point of view. We'll excise the number 2 later down the line!

2025-01-22 09:26 UTC, wdeconinck commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    xyz = lfric_rotations_[tile].transpose() * tan_point;
😮

2025-01-23 15:18 UTC, mo-jonasganderton commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    xyz = lfric_rotations_[tile].transpose() * tan_point;
Done! I've left the original rotations in for now in case we need them later.

2025-01-23 15:55 UTC, wdeconinck commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    return {xyz(0), xyz(1), xyz(2)};
I guess this can be unrolled avoiding any temporary `Vector` and also removes the need for a maths library.
```c++
PointXYZ xyz;
const auto& mat = lfric_rotations_transposed_[tile];
// xyz = mat * Vector{tan_coord[0], tan_coord[1], 1}
xyz[0] = mat(0,0) * tan_coord[0] + mat(0,1) * tan_coord[1] + mat(0,2);
xyz[1] = mat(1,0) * tan_coord[0] + mat(1,1) * tan_coord[1] + mat(1,2);
xyz[2] = mat(2,0) * tan_coord[0] + mat(2,1) * tan_coord[1] + mat(2,2);
xyz.normalize();
return xyz;

2025-01-23 16:00 UTC, wdeconinck commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    return {xyz(0), xyz(1), xyz(2)};
Apologies to return to this again. It is just much better to avoid any object that may be causing allocations. I think that's the case when Eigen is not used. Also the Matrix type could now just be in fact a `std::array<std::array<double,3>,3>` and we don't need to include any eckit/maths or Eigen in `CubedSphere2.h`

2025-01-23 16:08 UTC, odlomax commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    return {xyz(0), xyz(1), xyz(2)};
I'm on board with this. It's probably my fault for falling into the trap of thinking ahead about things we might not actually need. An array of arrays is more portable and easy enough to invert if needed.

2025-01-23 16:16 UTC, wdeconinck commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    return {xyz(0), xyz(1), xyz(2)};
It is also always possible to create a non-owning Eigen Matrix view of std::array<std::array<double,3>,3> if you so desire :)

2025-01-23 18:03 UTC, mo-jonasganderton commented on src/atlas/grid/detail/grid/CubedSphere2.cc
> +    return {xyz(0), xyz(1), xyz(2)};
All done!

2025-01-24 08:17 UTC, wdeconinck approved these changes
Fantastic

2025-01-24 12:44 UTC, merged