Cubed sphere bilinear interpolation
ecmwf/atlas pull request #98
Opened 2022-03-16 14:57 UTC by odlomax

This feature adds following functionality:

* a "cubedsphere-bilinear" interpolation scheme, with an associated "cubedsphere" MatchingMesh partitioner.
* adjoint-of-halo-exchange functionality to the NodeColumns functionspace.
* a general tidy-up of Quad2D and Triag2D interpolation elements, with some extra floating-point epsilon checks.
* a cubed sphere interpolation test which uses all of the above. (Example shown below).

CS-LFR-24 interpolation source field:
![source](https://user-images.githubusercontent.com/20695114/158619459-738433ce-eba5-4b70-a40d-7c3816d8de79.png)

O24 interpolation target field:
![target](https://user-images.githubusercontent.com/20695114/158619509-8f74fa0b-afb4-4f8b-9a5e-92fc89c4221c.png)

@wdeconinck and @MarekWlasak I basically copy-and-pasted code from StructuredColumns to NodeColumns to get the adjoint of the halo exchange to work. Can you check that I haven't done something truly daft?

2022-03-24 14:25 UTC, wdeconinck requested changes
Thank you @odlomax this is very high quality code with only very few suggestions.

I have however concerns about the changes to interpolation/element files:
- changes to solveQuadratic function
- changes to the inTriangle and inQuadrilateral methods
- changes or introduction of epsilons
I am not sure what the repercussions are on computations of intersections.
Could you elaborate why the changes were necessary?
If important, perhaps these changes merit a separate PR for which we need to test carefully the impact on operational product generation results and introduce a backward compatible mode, or be able to cleanly revert.
Requesting @pmaciel input on this as well.

2022-03-24 14:25 UTC, wdeconinck commented on src/tests/interpolation/CMakeLists.txt
> +  CONDITION eckit_HAVE_MPI AND MPI_SLOTS GREATER_EQUAL 6 AND eckit_EIGEN_FOUND
Why is eckit_EIGEN_FOUND important?

2022-03-25 10:20 UTC, odlomax commented on src/tests/interpolation/CMakeLists.txt
> +  CONDITION eckit_HAVE_MPI AND MPI_SLOTS GREATER_EQUAL 6 AND eckit_EIGEN_FOUND
Whoops. It isn't!

2022-03-25 11:26 UTC, odlomax commented
> Thank you @odlomax this is very high quality code with only very few suggestions.
> 
> I have however concerns about the changes to interpolation/element files:
> 
> * changes to solveQuadratic function
> * changes to the inTriangle and inQuadrilateral methods
> * changes or introduction of epsilons
>   I am not sure what the repercussions are on computations of intersections.
>   Could you elaborate why the changes were necessary?
>   If important, perhaps these changes merit a separate PR for which we need to test carefully the impact on operational product generation results and introduce a backward compatible mode, or be able to cleanly revert.
>   Requesting @pmaciel input on this as well.

Thanks, @wdeconinck!

I've rolled back the elements to what they were. You're right, I shouldn't have changed them here. I'll investigate properly and raise an issue if I find something unusual.

2022-03-25 12:17 UTC, wdeconinck approved these changes
Thanks for addressing all suggestions!

2022-03-25 12:22 UTC, merged